### ISSUE TITLE
Question about the project situation and plans

### ISSUE THREAD

**Issue by DagA11y** [it-vegard/a11y-reference-website#102]
Hi, is this project still alive?

I was thinking to do some contributions but it appears that nobody took care of existing pull requests & issues, so just wanted to check?

Also wonder if there are any plans to continue with development (I've read that universities will be using it).

I really like the idea of a modern "before and after" page that can replace the official one from 2012 (https://www.w3.org/WAI/demos/bad/after/home.html)...

Hope to hear from authors...

**Comment by it-vegard** [comment]
Hi,

I just answered your question on web-a11y.slack.com, but will answer here for transparency/others interested.

Yes, the project lives. I've just been in a "slumber" because of the pandemic, home situation and being busy with my day-time job, and somehow haven't received any emails about incoming issues or PRs to this repo. Really sorry about that!

As mentioned, the project is used in a couple of study-programs at universities here in Norway, so I just need to make sure changes don't break their assignments. But I have just started checking on the status for these programs, and hope to be able to begin reviewing and accepting PRs this week or the next. After this, I will make an effort to follow up regularly.

I have also thought some on the possibility of moving this "protected" version of the project (stable for the university programs) to a branch deploy (we're using Netlify, so that should be easy), so we can make more rapid changes to clothes4all.net.

I'll follow up here in a few days, when I have clarified that it is okay to start making changes to the website again.

**Comment by DagA11y** [comment]
Hi, thanks, answered there and copy/pasting it here as well;

... thank you very much for this explanation. I totally get it and appreciate your honesty and such a great initiative.
Will do some more PR's, have some ideas and there are some small bugs that need attention.
It's a very good initiative and I hope many from this Slack channel can contribute. Maybe some companies can even join the good cause.
It's in English and in Norwegian and other languages can be also added, so can serve many learning and teaching accessibility.
Getting accessibility into academia was something I personally missed and I guess they can maybe have their own repo, kind of "Long Term Support" while others can work on the more progressive repo?
As an open source we can maybe also have multiple folks attending the PR's etc.
Thanks again and kind regards.
